version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: calculator-db
    restart: always
    environment:
      # make sure your DB_PASSWORD is correct mine is root
      MYSQL_ROOT_PASSWORD: calc_password
      MYSQL_DATABASE: calc_data
      MYSQL_USER: calc_appuser
      MYSQL_PASSWORD: calc_password
      # Make sure your 3307 port is available
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    # image is my own account for the exercise you have to change to your account
    #IMPORTANT docker build -t yourname/sum-product-fx .
    # docker push yourname/sum-product-fx: last
    # then you can change the image in the following statment
    build:
      context: .
      dockerfile: Dockerfile
    image: zakkedocker/sum-product_fx
    container_name: calculator-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      # make sure your DB_USER name is correct mine is root
      DB_USER: calc_appuser
      # make sure your DB_PASSWORD is correct mine is root
      DB_PASSWORD: calc_password
      DISPLAY: host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
#    network_mode: bridge # it cancels network of docker -> docker cannot find host db.
volumes:
  db_data:

#  Then execute docker compose up --build
